pipeline {
    agent any

    triggers {
        pollSCM('H * * * *')
    }

    stages {
        stage('Dependencies') {
            steps {
                sh '''
                curl -O https://dot.net/v1/dotnet-install.sh
                chmod +x ./dotnet-install.sh
                ./dotnet-install.sh --version latest
                '''
            }
        }
        stage('Build') {
            steps {
                dir('CICD') {
                    sh '''
                    dotnet build
                    '''
                }
            }
        }
        stage('Test') {
            steps {
                sh "dotnet test"
            }
        }

        stage('Deploy') {
            steps {
                sh "dotnet deploy"
            }
        }
    }
}
