pipeline {
    agent any

    triggers {
        pollSCM('H * * * 1-5')
    }

    stages {
        stage('Build') {
            steps {
                sh ```
                ls
                pwd
                dotnet test .
                ```
            }
        }
        stage('Test') {
            steps {

                // Run Maven on a Unix agent.
                sh "dotnet test ."
            }
        }

        stage('Deploy') {
            steps {

                // Run Maven on a Unix agent.
                sh "dotnet deploy"
            }
        }
    }
}
